name: Deploy Front-end

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build
      working-directory: ./Front-end-PTR

    - name: Deploy to primary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_PRIMARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r Front-end-PTR/dist/* /var/www/html/
          sudo systemctl restart nginx
          pm2 restart all
      env:
        NPM_CONFIG_PREFIX: ~/npm-global

    - name: Deploy to secondary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_SECONDARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r Front-end-PTR/dist/* /var/www/html/
          sudo systemctl restart nginx
          pm2 restart all
      env:
        NPM_CONFIG_PREFIX: ~/npm-global
