name: Deploy Front-end

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current directory
      run: pwd

    - name: List files
      run: ls -al

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to primary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_PRIMARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/reclaim4242/Front-end-PTR/dist/* /var/www/html/
          sudo systemctl restart nginx
          pm2 restart all
        debug: true
    - name: Deploy to secondary server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_SECONDARY }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/reclaim4242/Front-end-PTR/dist/* /var/www/html/
          sudo systemctl restart nginx
          pm2 restart all
